# Generated by Django 6.0 on 2026-02-05 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('institution_login', 'Institution Admin Login'), ('institution_logout', 'Institution Admin Logout'), ('class_created', 'Class Created'), ('class_edited', 'Class Edited'), ('class_deleted', 'Class Deleted'), ('student_added', 'Student Added'), ('student_updated', 'Student Updated'), ('student_deleted', 'Student Deleted'), ('subject_added', 'Subject Added'), ('subject_updated', 'Subject Updated'), ('subject_deleted', 'Subject Deleted'), ('attendance_taken', 'Attendance Taken'), ('marks_entered', 'Marks Entered'), ('evaluation_created', 'Evaluation Created'), ('announcement_posted', 'Announcement Posted'), ('quiz_created', 'Quiz Created'), ('profile_updated', 'Profile Updated'), ('account_created', 'Account Created'), ('account_disabled', 'Account Disabled'), ('report_generated', 'Report Generated'), ('data_exported', 'Data Exported'), ('other', 'Other Action')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, help_text='Additional details about the action', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('related_object_id', models.PositiveIntegerField(blank=True, help_text='ID of related object (e.g., class ID, student ID)', null=True)),
                ('related_object_type', models.CharField(blank=True, help_text='Type of related object (e.g., Class, Student, Subject)', max_length=50, null=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='main.institution')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='main.users')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='main_auditl_user_id_5c7864_idx'), models.Index(fields=['action', '-timestamp'], name='main_auditl_action_17a227_idx'), models.Index(fields=['institution', '-timestamp'], name='main_auditl_institu_2166ee_idx')],
            },
        ),
    ]
