# Generated by Django 6.0 on 2026-02-05 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auditlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessLog',
        ),
    ]
