# Generated by Django 6.0 on 2026-02-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auditlog_delete_accesslog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='class_abbreviation',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
