# Generated by Django 6.0 on 2026-03-10 06:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_classes_class_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
