# Generated by Django 6.0 on 2026-03-12 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_chat_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='is_read',
        ),
    ]
