# Generated by Django 6.0 on 2026-03-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_announcements_is_read_announcementread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='class_abbreviation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
