# Generated by Django 6.0 on 2026-03-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_classes_class_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementread',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_head',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='classes',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='classes',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='institution',
            name='institution_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='institution',
            name='institution_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='institution',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='marks',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parents',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parents',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parents',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='option_a',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='option_b',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='option_c',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='option_d',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quizresponse',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='students',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studymaterials',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subject_head',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subject_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
