# Generated by Django 6.0 on 2026-03-29 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_announcementread_id_alter_announcements_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marks',
        ),
    ]
