# Generated by Django 6.0 on 2026-07-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_delete_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='password',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='institution',
            name='password',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='parents',
            name='password',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='password',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='password',
            field=models.CharField(),
        ),
    ]
